apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bad-image
spec:
  template:
    metadata:
      labels:
        name: bad-image
    spec:
      containers:
      - name: bad-image
        image: bluematador/bad-image:bad-tag
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "200m"
