apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo-server
spec:
  template:
    metadata:
      labels:
        name: echo-server
    spec:
      containers:
      - name: echo-server
        image: k8s.gcr.io/echoserver:1.8
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"
