apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oom
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: oom
    spec:
      containers:
      - name: oom
        image: stephanlindauer/docker-memory-leak:latest
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "250Mi"
            cpu: "250m"
